apiVersion: v1
kind: Secret
metadata:
  name: the-forge-secret
  namespace: maze-prod
type: Opaque
stringData:
  THE_FORGE_SERVER_JWT_SECRET: 'CHANGE-ME-IN-PRODUCTION'
  DATABASE_USER: 'maze'
  DATABASE_PASSWORD: 'CHANGE-ME-IN-PRODUCTION'
