// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: casbin.sql

package gen

import (
	"context"
)

const deleteCasbinRule = `-- name: DeleteCasbinRule :exec
DELETE FROM auth.casbin_rules
WHERE id = $1
`

func (q *Queries) DeleteCasbinRule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCasbinRule, id)
	return err
}

const insertCasbinRule = `-- name: InsertCasbinRule :one
INSERT INTO auth.casbin_rules (ptype, v0, v1, v2)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertCasbinRuleParams struct {
	Ptype string  `json:"ptype"`
	V0    *string `json:"v0"`
	V1    *string `json:"v1"`
	V2    *string `json:"v2"`
}

func (q *Queries) InsertCasbinRule(ctx context.Context, arg InsertCasbinRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCasbinRule,
		arg.Ptype,
		arg.V0,
		arg.V1,
		arg.V2,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAllCasbinRules = `-- name: ListAllCasbinRules :many
SELECT id, ptype, v0, v1, v2, v3, v4, v5
FROM auth.casbin_rules
ORDER BY id ASC
`

func (q *Queries) ListAllCasbinRules(ctx context.Context) ([]AuthCasbinRule, error) {
	rows, err := q.db.Query(ctx, listAllCasbinRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthCasbinRule
	for rows.Next() {
		var i AuthCasbinRule
		if err := rows.Scan(
			&i.ID,
			&i.Ptype,
			&i.V0,
			&i.V1,
			&i.V2,
			&i.V3,
			&i.V4,
			&i.V5,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
