// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthPermissionGrantStatus string

const (
	AuthPermissionGrantStatusActive  AuthPermissionGrantStatus = "active"
	AuthPermissionGrantStatusRevoked AuthPermissionGrantStatus = "revoked"
	AuthPermissionGrantStatusExpired AuthPermissionGrantStatus = "expired"
)

func (e *AuthPermissionGrantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthPermissionGrantStatus(s)
	case string:
		*e = AuthPermissionGrantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthPermissionGrantStatus: %T", src)
	}
	return nil
}

type NullAuthPermissionGrantStatus struct {
	AuthPermissionGrantStatus AuthPermissionGrantStatus `json:"auth_permission_grant_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if AuthPermissionGrantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthPermissionGrantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuthPermissionGrantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthPermissionGrantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthPermissionGrantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthPermissionGrantStatus), nil
}

type AuthPermissionRequestStatus string

const (
	AuthPermissionRequestStatusPending  AuthPermissionRequestStatus = "pending"
	AuthPermissionRequestStatusApproved AuthPermissionRequestStatus = "approved"
	AuthPermissionRequestStatusDenied   AuthPermissionRequestStatus = "denied"
	AuthPermissionRequestStatusRevoked  AuthPermissionRequestStatus = "revoked"
	AuthPermissionRequestStatusExpired  AuthPermissionRequestStatus = "expired"
)

func (e *AuthPermissionRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthPermissionRequestStatus(s)
	case string:
		*e = AuthPermissionRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthPermissionRequestStatus: %T", src)
	}
	return nil
}

type NullAuthPermissionRequestStatus struct {
	AuthPermissionRequestStatus AuthPermissionRequestStatus `json:"auth_permission_request_status"`
	Valid                       bool                        `json:"valid"` // Valid is true if AuthPermissionRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthPermissionRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuthPermissionRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthPermissionRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthPermissionRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthPermissionRequestStatus), nil
}

type AuthAuditLog struct {
	ID               int64              `json:"id"`
	Action           string             `json:"action"`
	ActorSubjectKey  *string            `json:"actor_subject_key"`
	TargetSubjectKey *string            `json:"target_subject_key"`
	RequestID        *int64             `json:"request_id"`
	DetailsJson      []byte             `json:"details_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type AuthCasbinRule struct {
	ID    int64   `json:"id"`
	Ptype string  `json:"ptype"`
	V0    *string `json:"v0"`
	V1    *string `json:"v1"`
	V2    *string `json:"v2"`
	V3    *string `json:"v3"`
	V4    *string `json:"v4"`
	V5    *string `json:"v5"`
}

type AuthPermissionGrant struct {
	ID              int64                     `json:"id"`
	PublicID        *string                   `json:"public_id"`
	SubjectKey      string                    `json:"subject_key"`
	Resource        string                    `json:"resource"`
	Action          string                    `json:"action"`
	SourceRequestID int64                     `json:"source_request_id"`
	CasbinRuleID    *int64                    `json:"casbin_rule_id"`
	Status          AuthPermissionGrantStatus `json:"status"`
	RevokedBy       *string                   `json:"revoked_by"`
	RevokedReason   *string                   `json:"revoked_reason"`
	ExpiresAt       pgtype.Timestamptz        `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz        `json:"updated_at"`
}

type AuthPermissionRequest struct {
	ID            int64                       `json:"id"`
	PublicID      *string                     `json:"public_id"`
	SubjectKey    string                      `json:"subject_key"`
	TargetsJson   []byte                      `json:"targets_json"`
	Reason        string                      `json:"reason"`
	Status        AuthPermissionRequestStatus `json:"status"`
	ReviewedBy    *string                     `json:"reviewed_by"`
	ReviewComment *string                     `json:"review_comment"`
	ReviewedAt    pgtype.Timestamptz          `json:"reviewed_at"`
	ExpiresAt     pgtype.Timestamptz          `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz          `json:"updated_at"`
}

type AuthSubject struct {
	SubjectKey  string             `json:"subject_key"`
	SubjectType string             `json:"subject_type"`
	DisplayName string             `json:"display_name"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
