// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_grants.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachGrantCasbinRule = `-- name: AttachGrantCasbinRule :one
UPDATE auth.permission_grants
SET casbin_rule_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, public_id, subject_key, resource, action, source_request_id, casbin_rule_id, status, revoked_by, revoked_reason, expires_at, created_at, updated_at
`

type AttachGrantCasbinRuleParams struct {
	ID           int64  `json:"id"`
	CasbinRuleID *int64 `json:"casbin_rule_id"`
}

func (q *Queries) AttachGrantCasbinRule(ctx context.Context, arg AttachGrantCasbinRuleParams) (AuthPermissionGrant, error) {
	row := q.db.QueryRow(ctx, attachGrantCasbinRule, arg.ID, arg.CasbinRuleID)
	var i AuthPermissionGrant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.Resource,
		&i.Action,
		&i.SourceRequestID,
		&i.CasbinRuleID,
		&i.Status,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePermissionGrant = `-- name: ExpirePermissionGrant :one
UPDATE auth.permission_grants
SET status = 'expired',
    updated_at = NOW()
WHERE id = $1
RETURNING id, public_id, subject_key, resource, action, source_request_id, casbin_rule_id, status, revoked_by, revoked_reason, expires_at, created_at, updated_at
`

func (q *Queries) ExpirePermissionGrant(ctx context.Context, id int64) (AuthPermissionGrant, error) {
	row := q.db.QueryRow(ctx, expirePermissionGrant, id)
	var i AuthPermissionGrant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.Resource,
		&i.Action,
		&i.SourceRequestID,
		&i.CasbinRuleID,
		&i.Status,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPermissionGrant = `-- name: InsertPermissionGrant :one
INSERT INTO auth.permission_grants (
    subject_key,
    resource,
    action,
    source_request_id,
    expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, subject_key, resource, action, source_request_id, casbin_rule_id, status, revoked_by, revoked_reason, expires_at, created_at, updated_at
`

type InsertPermissionGrantParams struct {
	SubjectKey      string             `json:"subject_key"`
	Resource        string             `json:"resource"`
	Action          string             `json:"action"`
	SourceRequestID int64              `json:"source_request_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertPermissionGrant(ctx context.Context, arg InsertPermissionGrantParams) (AuthPermissionGrant, error) {
	row := q.db.QueryRow(ctx, insertPermissionGrant,
		arg.SubjectKey,
		arg.Resource,
		arg.Action,
		arg.SourceRequestID,
		arg.ExpiresAt,
	)
	var i AuthPermissionGrant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.Resource,
		&i.Action,
		&i.SourceRequestID,
		&i.CasbinRuleID,
		&i.Status,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSubjectPermissionGrants = `-- name: ListActiveSubjectPermissionGrants :many
SELECT
    g.id, g.public_id, g.subject_key, g.resource, g.action, g.source_request_id, g.casbin_rule_id, g.status, g.revoked_by, g.revoked_reason, g.expires_at, g.created_at, g.updated_at,
    pr.public_id AS source_request_public_id
FROM auth.permission_grants AS g
JOIN auth.permission_requests AS pr ON pr.id = g.source_request_id
WHERE g.subject_key = $1 AND g.status = 'active'
ORDER BY g.created_at DESC
`

type ListActiveSubjectPermissionGrantsRow struct {
	AuthPermissionGrant   AuthPermissionGrant `json:"auth_permission_grant"`
	SourceRequestPublicID *string             `json:"source_request_public_id"`
}

func (q *Queries) ListActiveSubjectPermissionGrants(ctx context.Context, subjectKey string) ([]ListActiveSubjectPermissionGrantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSubjectPermissionGrants, subjectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubjectPermissionGrantsRow
	for rows.Next() {
		var i ListActiveSubjectPermissionGrantsRow
		if err := rows.Scan(
			&i.AuthPermissionGrant.ID,
			&i.AuthPermissionGrant.PublicID,
			&i.AuthPermissionGrant.SubjectKey,
			&i.AuthPermissionGrant.Resource,
			&i.AuthPermissionGrant.Action,
			&i.AuthPermissionGrant.SourceRequestID,
			&i.AuthPermissionGrant.CasbinRuleID,
			&i.AuthPermissionGrant.Status,
			&i.AuthPermissionGrant.RevokedBy,
			&i.AuthPermissionGrant.RevokedReason,
			&i.AuthPermissionGrant.ExpiresAt,
			&i.AuthPermissionGrant.CreatedAt,
			&i.AuthPermissionGrant.UpdatedAt,
			&i.SourceRequestPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPermissionGrants = `-- name: ListExpiredPermissionGrants :many
SELECT
    g.id, g.public_id, g.subject_key, g.resource, g.action, g.source_request_id, g.casbin_rule_id, g.status, g.revoked_by, g.revoked_reason, g.expires_at, g.created_at, g.updated_at,
    pr.public_id AS source_request_public_id
FROM auth.permission_grants AS g
JOIN auth.permission_requests AS pr ON pr.id = g.source_request_id
WHERE g.status = 'active' AND g.expires_at IS NOT NULL AND g.expires_at <= NOW()
ORDER BY g.expires_at ASC
`

type ListExpiredPermissionGrantsRow struct {
	AuthPermissionGrant   AuthPermissionGrant `json:"auth_permission_grant"`
	SourceRequestPublicID *string             `json:"source_request_public_id"`
}

func (q *Queries) ListExpiredPermissionGrants(ctx context.Context) ([]ListExpiredPermissionGrantsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPermissionGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredPermissionGrantsRow
	for rows.Next() {
		var i ListExpiredPermissionGrantsRow
		if err := rows.Scan(
			&i.AuthPermissionGrant.ID,
			&i.AuthPermissionGrant.PublicID,
			&i.AuthPermissionGrant.SubjectKey,
			&i.AuthPermissionGrant.Resource,
			&i.AuthPermissionGrant.Action,
			&i.AuthPermissionGrant.SourceRequestID,
			&i.AuthPermissionGrant.CasbinRuleID,
			&i.AuthPermissionGrant.Status,
			&i.AuthPermissionGrant.RevokedBy,
			&i.AuthPermissionGrant.RevokedReason,
			&i.AuthPermissionGrant.ExpiresAt,
			&i.AuthPermissionGrant.CreatedAt,
			&i.AuthPermissionGrant.UpdatedAt,
			&i.SourceRequestPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionGrantsByRequest = `-- name: ListPermissionGrantsByRequest :many
SELECT id, public_id, subject_key, resource, action, source_request_id, casbin_rule_id, status, revoked_by, revoked_reason, expires_at, created_at, updated_at
FROM auth.permission_grants
WHERE source_request_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPermissionGrantsByRequest(ctx context.Context, sourceRequestID int64) ([]AuthPermissionGrant, error) {
	rows, err := q.db.Query(ctx, listPermissionGrantsByRequest, sourceRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthPermissionGrant
	for rows.Next() {
		var i AuthPermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SubjectKey,
			&i.Resource,
			&i.Action,
			&i.SourceRequestID,
			&i.CasbinRuleID,
			&i.Status,
			&i.RevokedBy,
			&i.RevokedReason,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActivePermissionGrantsByRequest = `-- name: RevokeActivePermissionGrantsByRequest :many
UPDATE auth.permission_grants
SET status = $2,
    revoked_by = $3,
    revoked_reason = $4,
    updated_at = NOW()
WHERE source_request_id = $1 AND status = 'active'
RETURNING id, public_id, subject_key, resource, action, source_request_id, casbin_rule_id, status, revoked_by, revoked_reason, expires_at, created_at, updated_at
`

type RevokeActivePermissionGrantsByRequestParams struct {
	SourceRequestID int64                     `json:"source_request_id"`
	Status          AuthPermissionGrantStatus `json:"status"`
	RevokedBy       *string                   `json:"revoked_by"`
	RevokedReason   *string                   `json:"revoked_reason"`
}

func (q *Queries) RevokeActivePermissionGrantsByRequest(ctx context.Context, arg RevokeActivePermissionGrantsByRequestParams) ([]AuthPermissionGrant, error) {
	rows, err := q.db.Query(ctx, revokeActivePermissionGrantsByRequest,
		arg.SourceRequestID,
		arg.Status,
		arg.RevokedBy,
		arg.RevokedReason,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthPermissionGrant
	for rows.Next() {
		var i AuthPermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SubjectKey,
			&i.Resource,
			&i.Action,
			&i.SourceRequestID,
			&i.CasbinRuleID,
			&i.Status,
			&i.RevokedBy,
			&i.RevokedReason,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
