apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/manager-pvc.yaml
  - manager-configmap.yaml

patches:
  - path: manager-deployment-patch.yaml
