apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: maze-prod
data:
  AGENT_MANAGER_RUNTIME_TYPE: 'kubernetes'
  AGENT_MANAGER_KUBERNETES_NAMESPACE: 'maze-prod'
  AGENT_MANAGER_KUBERNETES_AGENT_IMAGE_PREFIX: 'REGISTRY/maze-agent'
  AGENT_MANAGER_KUBERNETES_AGENT_IMAGE_TAG: 'VERSION'
  AGENT_MANAGER_KUBERNETES_IMAGE_PULL_POLICY: 'IfNotPresent'
  AGENT_MANAGER_KUBERNETES_MANAGER_ADDR: 'agent-manager.maze-prod.svc.cluster.local:8080'
  AGENT_MANAGER_KUBERNETES_PVC_SIZE: '10Gi'
  AGENT_MANAGER_KUBERNETES_VOLUME_TYPE: 'pvc'
  AGENT_MANAGER_ALLOW_PRIVATE_NETWORKS: 'true'
  AGENT_MANAGER_WORKSPACE_BASE_DIR: '/data'
  AGENT_MANAGER_WORKSPACE_MOUNT_DIR: '/data'
