apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maze-dev

resources:
  - ../../base
  - manager-configmap.yaml
  - manager-deployment.yaml

patches:
  - target:
      kind: Namespace
      name: maze-prod
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: maze-prod
  - target:
      kind: ConfigMap
      name: web-nginx-config
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: web-nginx-config
      data:
        MANAGER_UPSTREAM: "agent-manager.maze-dev.svc.cluster.local:8080"
  - target:
      kind: PersistentVolumeClaim
      name: manager-data
    patch: |
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: manager-data
