apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maze-dev

resources:
  - ../../base
  - director-core-configmap.yaml
  - director-core-deployment.yaml
  - postgres.yaml

patches:
  - target:
      kind: Namespace
      name: maze-prod
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: maze-prod
  - target:
      kind: ConfigMap
      name: web-nginx-config
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: web-nginx-config
      data:
        DIRECTOR_CORE_UPSTREAM: "director-core.maze-dev.svc.cluster.local:8080"
  - target:
      kind: PersistentVolumeClaim
      name: director-core-data
    patch: |
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: director-core-data
