// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package gen

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO auth.audit_logs (
    action,
    actor_subject_key,
    target_subject_key,
    request_id,
    details_json
) VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	Action           string  `json:"action"`
	ActorSubjectKey  *string `json:"actor_subject_key"`
	TargetSubjectKey *string `json:"target_subject_key"`
	RequestID        *int64  `json:"request_id"`
	DetailsJson      []byte  `json:"details_json"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Action,
		arg.ActorSubjectKey,
		arg.TargetSubjectKey,
		arg.RequestID,
		arg.DetailsJson,
	)
	return err
}
