// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_requests.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPermissionRequestsAll = `-- name: CountPermissionRequestsAll :one
SELECT COUNT(*)
FROM auth.permission_requests
`

func (q *Queries) CountPermissionRequestsAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissionRequestsAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPermissionRequestsByStatus = `-- name: CountPermissionRequestsByStatus :one
SELECT COUNT(*)
FROM auth.permission_requests
WHERE status = $1
`

func (q *Queries) CountPermissionRequestsByStatus(ctx context.Context, status AuthPermissionRequestStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissionRequestsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPermissionRequestByPublicID = `-- name: GetPermissionRequestByPublicID :one
SELECT id, public_id, subject_key, targets_json, reason, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
FROM auth.permission_requests
WHERE public_id = $1
`

func (q *Queries) GetPermissionRequestByPublicID(ctx context.Context, publicID *string) (AuthPermissionRequest, error) {
	row := q.db.QueryRow(ctx, getPermissionRequestByPublicID, publicID)
	var i AuthPermissionRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.TargetsJson,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPermissionRequest = `-- name: InsertPermissionRequest :one
INSERT INTO auth.permission_requests (
    subject_key,
    targets_json,
    reason,
    expires_at
) VALUES ($1, $2, $3, $4)
RETURNING id, public_id, subject_key, targets_json, reason, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
`

type InsertPermissionRequestParams struct {
	SubjectKey  string             `json:"subject_key"`
	TargetsJson []byte             `json:"targets_json"`
	Reason      string             `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertPermissionRequest(ctx context.Context, arg InsertPermissionRequestParams) (AuthPermissionRequest, error) {
	row := q.db.QueryRow(ctx, insertPermissionRequest,
		arg.SubjectKey,
		arg.TargetsJson,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i AuthPermissionRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.TargetsJson,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissionRequestsAll = `-- name: ListPermissionRequestsAll :many
SELECT id, public_id, subject_key, targets_json, reason, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
FROM auth.permission_requests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPermissionRequestsAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPermissionRequestsAll(ctx context.Context, arg ListPermissionRequestsAllParams) ([]AuthPermissionRequest, error) {
	rows, err := q.db.Query(ctx, listPermissionRequestsAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthPermissionRequest
	for rows.Next() {
		var i AuthPermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SubjectKey,
			&i.TargetsJson,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.ReviewedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionRequestsByStatus = `-- name: ListPermissionRequestsByStatus :many
SELECT id, public_id, subject_key, targets_json, reason, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
FROM auth.permission_requests
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPermissionRequestsByStatusParams struct {
	Status AuthPermissionRequestStatus `json:"status"`
	Limit  int32                       `json:"limit"`
	Offset int32                       `json:"offset"`
}

func (q *Queries) ListPermissionRequestsByStatus(ctx context.Context, arg ListPermissionRequestsByStatusParams) ([]AuthPermissionRequest, error) {
	rows, err := q.db.Query(ctx, listPermissionRequestsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthPermissionRequest
	for rows.Next() {
		var i AuthPermissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SubjectKey,
			&i.TargetsJson,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.ReviewedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewPermissionRequest = `-- name: ReviewPermissionRequest :one
UPDATE auth.permission_requests
SET status = $1,
    reviewed_by = $2,
    review_comment = $3,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $4
  AND status = $5
RETURNING id, public_id, subject_key, targets_json, reason, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
`

type ReviewPermissionRequestParams struct {
	Status         AuthPermissionRequestStatus `json:"status"`
	ReviewedBy     *string                     `json:"reviewed_by"`
	ReviewComment  *string                     `json:"review_comment"`
	ID             int64                       `json:"id"`
	ExpectedStatus AuthPermissionRequestStatus `json:"expected_status"`
}

func (q *Queries) ReviewPermissionRequest(ctx context.Context, arg ReviewPermissionRequestParams) (AuthPermissionRequest, error) {
	row := q.db.QueryRow(ctx, reviewPermissionRequest,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewComment,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i AuthPermissionRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.TargetsJson,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePermissionRequestStatus = `-- name: UpdatePermissionRequestStatus :one
UPDATE auth.permission_requests
SET status = $2,
    reviewed_by = $3,
    review_comment = $4,
    reviewed_at = CASE
        WHEN $3 IS NULL THEN reviewed_at
        ELSE NOW()
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, public_id, subject_key, targets_json, reason, status, reviewed_by, review_comment, reviewed_at, expires_at, created_at, updated_at
`

type UpdatePermissionRequestStatusParams struct {
	ID            int64                       `json:"id"`
	Status        AuthPermissionRequestStatus `json:"status"`
	ReviewedBy    *string                     `json:"reviewed_by"`
	ReviewComment *string                     `json:"review_comment"`
}

func (q *Queries) UpdatePermissionRequestStatus(ctx context.Context, arg UpdatePermissionRequestStatusParams) (AuthPermissionRequest, error) {
	row := q.db.QueryRow(ctx, updatePermissionRequestStatus,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewComment,
	)
	var i AuthPermissionRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SubjectKey,
		&i.TargetsJson,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
