// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package gen

import (
	"context"
)

const getSubject = `-- name: GetSubject :one
SELECT subject_key, subject_type, display_name, is_system, created_at, updated_at
FROM auth.subjects
WHERE subject_key = $1
`

func (q *Queries) GetSubject(ctx context.Context, subjectKey string) (AuthSubject, error) {
	row := q.db.QueryRow(ctx, getSubject, subjectKey)
	var i AuthSubject
	err := row.Scan(
		&i.SubjectKey,
		&i.SubjectType,
		&i.DisplayName,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubject = `-- name: UpsertSubject :one
INSERT INTO auth.subjects (
    subject_key,
    subject_type,
    display_name,
    is_system,
    updated_at
) VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (subject_key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    is_system = EXCLUDED.is_system,
    updated_at = NOW()
RETURNING subject_key, subject_type, display_name, is_system, created_at, updated_at
`

type UpsertSubjectParams struct {
	SubjectKey  string `json:"subject_key"`
	SubjectType string `json:"subject_type"`
	DisplayName string `json:"display_name"`
	IsSystem    bool   `json:"is_system"`
}

func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (AuthSubject, error) {
	row := q.db.QueryRow(ctx, upsertSubject,
		arg.SubjectKey,
		arg.SubjectType,
		arg.DisplayName,
		arg.IsSystem,
	)
	var i AuthSubject
	err := row.Scan(
		&i.SubjectKey,
		&i.SubjectType,
		&i.DisplayName,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
