// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_entries.sql

package hostgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT COUNT(*) FROM audit_entries
`

func (q *Queries) CountAuditEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_entries (audit_id, timestamp, operator, target_node, action, payload_summary, result, status_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditEntryParams struct {
	AuditID        string             `json:"audit_id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	Operator       string             `json:"operator"`
	TargetNode     string             `json:"target_node"`
	Action         string             `json:"action"`
	PayloadSummary string             `json:"payload_summary"`
	Result         string             `json:"result"`
	StatusCode     int32              `json:"status_code"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.AuditID,
		arg.Timestamp,
		arg.Operator,
		arg.TargetNode,
		arg.Action,
		arg.PayloadSummary,
		arg.Result,
		arg.StatusCode,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, audit_id, timestamp, operator, target_node, action, payload_summary, result, status_code FROM audit_entries ORDER BY timestamp DESC
`

func (q *Queries) ListAuditEntries(ctx context.Context) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.Timestamp,
			&i.Operator,
			&i.TargetNode,
			&i.Action,
			&i.PayloadSummary,
			&i.Result,
			&i.StatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesPage = `-- name: ListAuditEntriesPage :many
SELECT id, audit_id, timestamp, operator, target_node, action, payload_summary, result, status_code FROM audit_entries
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListAuditEntriesPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEntriesPage(ctx context.Context, arg ListAuditEntriesPageParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.Timestamp,
			&i.Operator,
			&i.TargetNode,
			&i.Action,
			&i.PayloadSummary,
			&i.Result,
			&i.StatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEntries = `-- name: QueryAuditEntries :many
SELECT id, audit_id, timestamp, operator, target_node, action, payload_summary, result, status_code FROM audit_entries
WHERE ($1::text = '' OR target_node LIKE '%' || $1 || '%')
  AND ($2::text = '' OR action LIKE '%' || $2 || '%')
ORDER BY timestamp DESC
`

type QueryAuditEntriesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) QueryAuditEntries(ctx context.Context, arg QueryAuditEntriesParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, queryAuditEntries, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.Timestamp,
			&i.Operator,
			&i.TargetNode,
			&i.Action,
			&i.PayloadSummary,
			&i.Result,
			&i.StatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
