// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_specs.sql

package hostgen

import (
	"context"
)

const deleteHostSpecByName = `-- name: DeleteHostSpecByName :exec
DELETE FROM host_specs WHERE name = $1
`

func (q *Queries) DeleteHostSpecByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteHostSpecByName, name)
	return err
}

const getHostSpecByName = `-- name: GetHostSpecByName :one
SELECT id, name, display_name, tools, resources, auth_token, status, error_msg, retry_count, created_at, updated_at FROM host_specs WHERE name = $1
`

func (q *Queries) GetHostSpecByName(ctx context.Context, name string) (HostSpec, error) {
	row := q.db.QueryRow(ctx, getHostSpecByName, name)
	var i HostSpec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Tools,
		&i.Resources,
		&i.AuthToken,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementHostSpecRetry = `-- name: IncrementHostSpecRetry :one
UPDATE host_specs
SET retry_count = retry_count + 1, updated_at = NOW()
WHERE name = $1
RETURNING id, name, display_name, tools, resources, auth_token, status, error_msg, retry_count, created_at, updated_at
`

func (q *Queries) IncrementHostSpecRetry(ctx context.Context, name string) (HostSpec, error) {
	row := q.db.QueryRow(ctx, incrementHostSpecRetry, name)
	var i HostSpec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Tools,
		&i.Resources,
		&i.AuthToken,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHostSpec = `-- name: InsertHostSpec :execrows
INSERT INTO host_specs (name, display_name, tools, resources, auth_token, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO NOTHING
`

type InsertHostSpecParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Tools       []byte `json:"tools"`
	Resources   []byte `json:"resources"`
	AuthToken   string `json:"auth_token"`
	Status      string `json:"status"`
}

func (q *Queries) InsertHostSpec(ctx context.Context, arg InsertHostSpecParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertHostSpec,
		arg.Name,
		arg.DisplayName,
		arg.Tools,
		arg.Resources,
		arg.AuthToken,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listHostSpecs = `-- name: ListHostSpecs :many
SELECT id, name, display_name, tools, resources, auth_token, status, error_msg, retry_count, created_at, updated_at FROM host_specs ORDER BY name ASC
`

func (q *Queries) ListHostSpecs(ctx context.Context) ([]HostSpec, error) {
	rows, err := q.db.Query(ctx, listHostSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostSpec
	for rows.Next() {
		var i HostSpec
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Tools,
			&i.Resources,
			&i.AuthToken,
			&i.Status,
			&i.ErrorMsg,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostSpecStatus = `-- name: UpdateHostSpecStatus :one
UPDATE host_specs
SET status = $2, error_msg = $3, updated_at = NOW()
WHERE name = $1
RETURNING id, name, display_name, tools, resources, auth_token, status, error_msg, retry_count, created_at, updated_at
`

type UpdateHostSpecStatusParams struct {
	Name     string `json:"name"`
	Status   string `json:"status"`
	ErrorMsg string `json:"error_msg"`
}

func (q *Queries) UpdateHostSpecStatus(ctx context.Context, arg UpdateHostSpecStatusParams) (HostSpec, error) {
	row := q.db.QueryRow(ctx, updateHostSpecStatus, arg.Name, arg.Status, arg.ErrorMsg)
	var i HostSpec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Tools,
		&i.Resources,
		&i.AuthToken,
		&i.Status,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
