// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archives.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArchive = `-- name: CreateArchive :one
INSERT INTO archives (name, description, icon, author)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, icon, author, created_at, updated_at
`

type CreateArchiveParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Author      string `json:"author"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (Archive, error) {
	row := q.db.QueryRow(ctx, createArchive,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Author,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArchive = `-- name: DeleteArchive :exec
DELETE FROM archives WHERE id = $1
`

func (q *Queries) DeleteArchive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArchive, id)
	return err
}

const getArchive = `-- name: GetArchive :one
SELECT id, name, description, icon, author, created_at, updated_at FROM archives WHERE id = $1
`

func (q *Queries) GetArchive(ctx context.Context, id pgtype.UUID) (Archive, error) {
	row := q.db.QueryRow(ctx, getArchive, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArchives = `-- name: ListArchives :many
SELECT id, name, description, icon, author, created_at, updated_at FROM archives ORDER BY created_at DESC
`

func (q *Queries) ListArchives(ctx context.Context) ([]Archive, error) {
	rows, err := q.db.Query(ctx, listArchives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArchive = `-- name: UpdateArchive :one
UPDATE archives
SET name = $2, description = $3, icon = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, icon, author, created_at, updated_at
`

type UpdateArchiveParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Icon        string      `json:"icon"`
}

func (q *Queries) UpdateArchive(ctx context.Context, arg UpdateArchiveParams) (Archive, error) {
	row := q.db.QueryRow(ctx, updateArchive,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
