// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_history.sql

package gen

import (
	"context"
)

const clearChatHistory = `-- name: ClearChatHistory :exec
DELETE FROM chat_history
`

func (q *Queries) ClearChatHistory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearChatHistory)
	return err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_history (role, content, tool_calls)
VALUES ($1, $2, $3)
RETURNING id, role, content, tool_calls, created_at
`

type CreateChatMessageParams struct {
	Role      string `json:"role"`
	Content   string `json:"content"`
	ToolCalls []byte `json:"tool_calls"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatHistory, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.Role, arg.Content, arg.ToolCalls)
	var i ChatHistory
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.CreatedAt,
	)
	return i, err
}

const listChatHistory = `-- name: ListChatHistory :many
SELECT id, role, content, tool_calls, created_at FROM chat_history ORDER BY created_at ASC
`

func (q *Queries) ListChatHistory(ctx context.Context) ([]ChatHistory, error) {
	rows, err := q.db.Query(ctx, listChatHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatHistory
	for rows.Next() {
		var i ChatHistory
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
