// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directives.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDirectives = `-- name: CountDirectives :one
SELECT count(*) FROM directives
WHERE (status = $1 OR $1 = '')
  AND (assignee = $2 OR $2 = '')
  AND (priority = $3 OR $3 = '')
  AND (visibility = $4 OR $4 = '')
`

type CountDirectivesParams struct {
	Status     string `json:"status"`
	Assignee   string `json:"assignee"`
	Priority   string `json:"priority"`
	Visibility string `json:"visibility"`
}

func (q *Queries) CountDirectives(ctx context.Context, arg CountDirectivesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectives,
		arg.Status,
		arg.Assignee,
		arg.Priority,
		arg.Visibility,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDirective = `-- name: CreateDirective :one
INSERT INTO directives (title, description, status, priority, assignee, author, require_doc_ids, narrative_id, archive_id, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, title, description, status, priority, assignee, author, require_doc_ids, narrative_id, archive_id, visibility, created_at, updated_at
`

type CreateDirectiveParams struct {
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	Status        string      `json:"status"`
	Priority      string      `json:"priority"`
	Assignee      string      `json:"assignee"`
	Author        string      `json:"author"`
	RequireDocIds []byte      `json:"require_doc_ids"`
	NarrativeID   string      `json:"narrative_id"`
	ArchiveID     pgtype.UUID `json:"archive_id"`
	Visibility    string      `json:"visibility"`
}

func (q *Queries) CreateDirective(ctx context.Context, arg CreateDirectiveParams) (Directive, error) {
	row := q.db.QueryRow(ctx, createDirective,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Author,
		arg.RequireDocIds,
		arg.NarrativeID,
		arg.ArchiveID,
		arg.Visibility,
	)
	var i Directive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Author,
		&i.RequireDocIds,
		&i.NarrativeID,
		&i.ArchiveID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDirective = `-- name: DeleteDirective :exec
DELETE FROM directives WHERE id = $1
`

func (q *Queries) DeleteDirective(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDirective, id)
	return err
}

const getDirective = `-- name: GetDirective :one
SELECT id, title, description, status, priority, assignee, author, require_doc_ids, narrative_id, archive_id, visibility, created_at, updated_at FROM directives WHERE id = $1
`

func (q *Queries) GetDirective(ctx context.Context, id pgtype.UUID) (Directive, error) {
	row := q.db.QueryRow(ctx, getDirective, id)
	var i Directive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Author,
		&i.RequireDocIds,
		&i.NarrativeID,
		&i.ArchiveID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDirectives = `-- name: ListDirectives :many
SELECT id, title, description, status, priority, assignee, author, require_doc_ids, narrative_id, archive_id, visibility, created_at, updated_at FROM directives
WHERE (status = $1 OR $1 = '')
  AND (assignee = $2 OR $2 = '')
  AND (priority = $3 OR $3 = '')
  AND (visibility = $4 OR $4 = '')
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListDirectivesParams struct {
	Status     string `json:"status"`
	Assignee   string `json:"assignee"`
	Priority   string `json:"priority"`
	Visibility string `json:"visibility"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListDirectives(ctx context.Context, arg ListDirectivesParams) ([]Directive, error) {
	rows, err := q.db.Query(ctx, listDirectives,
		arg.Status,
		arg.Assignee,
		arg.Priority,
		arg.Visibility,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directive
	for rows.Next() {
		var i Directive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Author,
			&i.RequireDocIds,
			&i.NarrativeID,
			&i.ArchiveID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectivesByDocID = `-- name: ListDirectivesByDocID :many
SELECT id, title, description, status, priority, assignee, author, require_doc_ids, narrative_id, archive_id, visibility, created_at, updated_at FROM directives
WHERE require_doc_ids @> to_jsonb($1::text)
ORDER BY created_at DESC
`

func (q *Queries) ListDirectivesByDocID(ctx context.Context, dollar_1 string) ([]Directive, error) {
	rows, err := q.db.Query(ctx, listDirectivesByDocID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directive
	for rows.Next() {
		var i Directive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Author,
			&i.RequireDocIds,
			&i.NarrativeID,
			&i.ArchiveID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirective = `-- name: UpdateDirective :one
UPDATE directives
SET title           = COALESCE($2, title),
    description     = COALESCE($3, description),
    status          = COALESCE($4, status),
    priority        = COALESCE($5, priority),
    assignee        = COALESCE($6, assignee),
    author          = COALESCE($7, author),
    require_doc_ids = COALESCE($8, require_doc_ids),
    narrative_id    = COALESCE($9, narrative_id),
    archive_id      = COALESCE($10, archive_id),
    visibility      = COALESCE($11, visibility),
    updated_at      = now()
WHERE id = $1
RETURNING id, title, description, status, priority, assignee, author, require_doc_ids, narrative_id, archive_id, visibility, created_at, updated_at
`

type UpdateDirectiveParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	Status        string      `json:"status"`
	Priority      string      `json:"priority"`
	Assignee      string      `json:"assignee"`
	Author        string      `json:"author"`
	RequireDocIds []byte      `json:"require_doc_ids"`
	NarrativeID   string      `json:"narrative_id"`
	ArchiveID     pgtype.UUID `json:"archive_id"`
	Visibility    string      `json:"visibility"`
}

func (q *Queries) UpdateDirective(ctx context.Context, arg UpdateDirectiveParams) (Directive, error) {
	row := q.db.QueryRow(ctx, updateDirective,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Author,
		arg.RequireDocIds,
		arg.NarrativeID,
		arg.ArchiveID,
		arg.Visibility,
	)
	var i Directive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Author,
		&i.RequireDocIds,
		&i.NarrativeID,
		&i.ArchiveID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
