// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_links.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO doc_links (source_id, target_id, relation_type)
VALUES ($1, $2, $3)
RETURNING id, source_id, target_id, relation_type, created_at
`

type CreateLinkParams struct {
	SourceID     pgtype.UUID `json:"source_id"`
	TargetID     pgtype.UUID `json:"target_id"`
	RelationType string      `json:"relation_type"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (DocLink, error) {
	row := q.db.QueryRow(ctx, createLink, arg.SourceID, arg.TargetID, arg.RelationType)
	var i DocLink
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM doc_links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, source_id, target_id, relation_type, created_at FROM doc_links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id pgtype.UUID) (DocLink, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i DocLink
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.RelationType,
		&i.CreatedAt,
	)
	return i, err
}

const getLinksBySource = `-- name: GetLinksBySource :many
SELECT dl.id, dl.source_id, dl.target_id, dl.relation_type, dl.created_at, d.title AS target_title
FROM doc_links dl
JOIN docs d ON d.id = dl.target_id
WHERE dl.source_id = $1
  AND (dl.relation_type = $2 OR $2 = '')
ORDER BY dl.created_at DESC
`

type GetLinksBySourceParams struct {
	SourceID     pgtype.UUID `json:"source_id"`
	RelationType string      `json:"relation_type"`
}

type GetLinksBySourceRow struct {
	ID           pgtype.UUID        `json:"id"`
	SourceID     pgtype.UUID        `json:"source_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	RelationType string             `json:"relation_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TargetTitle  string             `json:"target_title"`
}

func (q *Queries) GetLinksBySource(ctx context.Context, arg GetLinksBySourceParams) ([]GetLinksBySourceRow, error) {
	rows, err := q.db.Query(ctx, getLinksBySource, arg.SourceID, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinksBySourceRow
	for rows.Next() {
		var i GetLinksBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.CreatedAt,
			&i.TargetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksByTarget = `-- name: GetLinksByTarget :many
SELECT dl.id, dl.source_id, dl.target_id, dl.relation_type, dl.created_at, d.title AS source_title
FROM doc_links dl
JOIN docs d ON d.id = dl.source_id
WHERE dl.target_id = $1
  AND (dl.relation_type = $2 OR $2 = '')
ORDER BY dl.created_at DESC
`

type GetLinksByTargetParams struct {
	TargetID     pgtype.UUID `json:"target_id"`
	RelationType string      `json:"relation_type"`
}

type GetLinksByTargetRow struct {
	ID           pgtype.UUID        `json:"id"`
	SourceID     pgtype.UUID        `json:"source_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	RelationType string             `json:"relation_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SourceTitle  string             `json:"source_title"`
}

func (q *Queries) GetLinksByTarget(ctx context.Context, arg GetLinksByTargetParams) ([]GetLinksByTargetRow, error) {
	rows, err := q.db.Query(ctx, getLinksByTarget, arg.TargetID, arg.RelationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinksByTargetRow
	for rows.Next() {
		var i GetLinksByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RelationType,
			&i.CreatedAt,
			&i.SourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
