// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docs.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocs = `-- name: CountDocs :one
SELECT count(*) FROM docs
WHERE ($1::uuid IS NULL OR archive_id = $1)
  AND ($2::uuid IS NULL OR parent_id = $2)
  AND ($3 = '' OR status = $3)
  AND ($4 = '' OR visibility = $4)
  AND ($5 = '' OR author = $5)
`

type CountDocsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) CountDocs(ctx context.Context, arg CountDocsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocsHasStatus = `-- name: CountDocsHasStatus :one
SELECT count(*) FROM docs
WHERE ($1::uuid IS NULL OR archive_id = $1)
  AND ($2::uuid IS NULL OR parent_id = $2)
  AND status IS NOT NULL
  AND ($3 = '' OR status = $3)
  AND ($4 = '' OR visibility = $4)
  AND ($5 = '' OR author = $5)
`

type CountDocsHasStatusParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) CountDocsHasStatus(ctx context.Context, arg CountDocsHasStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocsHasStatus,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDoc = `-- name: CreateDoc :one
INSERT INTO docs (archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at
`

type CreateDocParams struct {
	ArchiveID   pgtype.UUID `json:"archive_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Summary     string      `json:"summary"`
	Status      *string     `json:"status"`
	Priority    *string     `json:"priority"`
	Assignee    string      `json:"assignee"`
	Tags        []byte      `json:"tags"`
	Author      string      `json:"author"`
	Visibility  string      `json:"visibility"`
	SharedWith  []byte      `json:"shared_with"`
	Attachments []byte      `json:"attachments"`
}

func (q *Queries) CreateDoc(ctx context.Context, arg CreateDocParams) (Doc, error) {
	row := q.db.QueryRow(ctx, createDoc,
		arg.ArchiveID,
		arg.ParentID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Tags,
		arg.Author,
		arg.Visibility,
		arg.SharedWith,
		arg.Attachments,
	)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.ArchiveID,
		&i.ParentID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Tags,
		&i.Author,
		&i.Visibility,
		&i.SharedWith,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoc = `-- name: DeleteDoc :exec
DELETE FROM docs WHERE id = $1
`

func (q *Queries) DeleteDoc(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDoc, id)
	return err
}

const getDoc = `-- name: GetDoc :one
SELECT id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM docs WHERE id = $1
`

func (q *Queries) GetDoc(ctx context.Context, id pgtype.UUID) (Doc, error) {
	row := q.db.QueryRow(ctx, getDoc, id)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.ArchiveID,
		&i.ParentID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Tags,
		&i.Author,
		&i.Visibility,
		&i.SharedWith,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocChildren = `-- name: GetDocChildren :many
SELECT id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM docs
WHERE parent_id = $1
ORDER BY title ASC
`

func (q *Queries) GetDocChildren(ctx context.Context, parentID pgtype.UUID) ([]Doc, error) {
	rows, err := q.db.Query(ctx, getDocChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocRootChildren = `-- name: GetDocRootChildren :many
SELECT id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM docs
WHERE parent_id IS NULL
  AND archive_id = $1
ORDER BY title ASC
`

func (q *Queries) GetDocRootChildren(ctx context.Context, archiveID pgtype.UUID) ([]Doc, error) {
	rows, err := q.db.Query(ctx, getDocRootChildren, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocs = `-- name: ListDocs :many
SELECT id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM docs
WHERE ($1::uuid IS NULL OR archive_id = $1)
  AND ($2::uuid IS NULL OR parent_id = $2)
  AND ($3 = '' OR status = $3)
  AND ($4 = '' OR visibility = $4)
  AND ($5 = '' OR author = $5)
ORDER BY title ASC, created_at DESC
LIMIT $6 OFFSET $7
`

type ListDocsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDocs(ctx context.Context, arg ListDocsParams) ([]Doc, error) {
	rows, err := q.db.Query(ctx, listDocs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsHasStatus = `-- name: ListDocsHasStatus :many
SELECT id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM docs
WHERE ($1::uuid IS NULL OR archive_id = $1)
  AND ($2::uuid IS NULL OR parent_id = $2)
  AND status IS NOT NULL
  AND ($3 = '' OR status = $3)
  AND ($4 = '' OR visibility = $4)
  AND ($5 = '' OR author = $5)
ORDER BY title ASC, created_at DESC
LIMIT $6 OFFSET $7
`

type ListDocsHasStatusParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDocsHasStatus(ctx context.Context, arg ListDocsHasStatusParams) ([]Doc, error) {
	rows, err := q.db.Query(ctx, listDocsHasStatus,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocs = `-- name: SearchDocs :many
SELECT id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM docs
WHERE search_vector @@ plainto_tsquery('simple', $1)
  AND (archive_id = $2 OR $2 IS NULL)
  AND (visibility = $3 OR $3 = '')
  AND (author = $4 OR $4 = '')
ORDER BY ts_rank(search_vector, plainto_tsquery('simple', $1)) DESC
`

type SearchDocsParams struct {
	PlaintoTsquery string      `json:"plainto_tsquery"`
	ArchiveID      pgtype.UUID `json:"archive_id"`
	Visibility     string      `json:"visibility"`
	Author         string      `json:"author"`
}

func (q *Queries) SearchDocs(ctx context.Context, arg SearchDocsParams) ([]Doc, error) {
	rows, err := q.db.Query(ctx, searchDocs,
		arg.PlaintoTsquery,
		arg.ArchiveID,
		arg.Visibility,
		arg.Author,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoc = `-- name: UpdateDoc :one
UPDATE docs
SET title       = COALESCE($1, title),
    content     = COALESCE($2, content),
    summary     = COALESCE($3, summary),
    status      = CASE WHEN $4::boolean THEN NULL ELSE COALESCE($5, status) END,
    priority    = CASE WHEN $6::boolean THEN NULL ELSE COALESCE($7, priority) END,
    assignee    = COALESCE($8, assignee),
    tags        = COALESCE($9, tags),
    visibility  = COALESCE($10, visibility),
    shared_with = COALESCE($11, shared_with),
    attachments = COALESCE($12, attachments),
    parent_id   = COALESCE($13, parent_id),
    updated_at  = now()
WHERE id = $14
RETURNING id, archive_id, parent_id, title, content, summary, status, priority, assignee, tags, author, visibility, shared_with, attachments, created_at, updated_at
`

type UpdateDocParams struct {
	Title         *string     `json:"title"`
	Content       *string     `json:"content"`
	Summary       *string     `json:"summary"`
	ClearStatus   *bool       `json:"clear_status"`
	Status        *string     `json:"status"`
	ClearPriority *bool       `json:"clear_priority"`
	Priority      *string     `json:"priority"`
	Assignee      *string     `json:"assignee"`
	Tags          []byte      `json:"tags"`
	Visibility    *string     `json:"visibility"`
	SharedWith    []byte      `json:"shared_with"`
	Attachments   []byte      `json:"attachments"`
	ParentID      pgtype.UUID `json:"parent_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDoc(ctx context.Context, arg UpdateDocParams) (Doc, error) {
	row := q.db.QueryRow(ctx, updateDoc,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.ClearStatus,
		arg.Status,
		arg.ClearPriority,
		arg.Priority,
		arg.Assignee,
		arg.Tags,
		arg.Visibility,
		arg.SharedWith,
		arg.Attachments,
		arg.ParentID,
		arg.ID,
	)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.ArchiveID,
		&i.ParentID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Tags,
		&i.Author,
		&i.Visibility,
		&i.SharedWith,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
