// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package gen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMemories = `-- name: CountMemories :one
SELECT count(*) FROM memories
WHERE (archive_id = $1 OR $1 IS NULL)
  AND (parent_id = $2 OR ($2 IS NULL AND parent_id IS NULL))
  AND (kind = $3 OR $3 = '')
  AND (type = $4 OR $4 = '')
  AND (visibility = $5 OR $5 = '')
  AND (author = $6 OR $6 = '')
`

type CountMemoriesParams struct {
	ArchiveID  pgtype.UUID `json:"archive_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Kind       string      `json:"kind"`
	Type       string      `json:"type"`
	Visibility string      `json:"visibility"`
	Author     string      `json:"author"`
}

func (q *Queries) CountMemories(ctx context.Context, arg CountMemoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemories,
		arg.ArchiveID,
		arg.ParentID,
		arg.Kind,
		arg.Type,
		arg.Visibility,
		arg.Author,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at
`

type CreateMemoryParams struct {
	ArchiveID   pgtype.UUID `json:"archive_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Kind        string      `json:"kind"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Summary     string      `json:"summary"`
	Type        string      `json:"type"`
	Tags        []byte      `json:"tags"`
	Author      string      `json:"author"`
	Visibility  string      `json:"visibility"`
	SharedWith  []byte      `json:"shared_with"`
	Attachments []byte      `json:"attachments"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.ArchiveID,
		arg.ParentID,
		arg.Kind,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Type,
		arg.Tags,
		arg.Author,
		arg.Visibility,
		arg.SharedWith,
		arg.Attachments,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.ArchiveID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Type,
		&i.Tags,
		&i.Author,
		&i.Visibility,
		&i.SharedWith,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = $1
`

func (q *Queries) DeleteMemory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMemory, id)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM memories WHERE id = $1
`

func (q *Queries) GetMemory(ctx context.Context, id pgtype.UUID) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.ArchiveID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Type,
		&i.Tags,
		&i.Author,
		&i.Visibility,
		&i.SharedWith,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryChildren = `-- name: GetMemoryChildren :many
SELECT id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM memories
WHERE parent_id = $1
ORDER BY kind ASC, title ASC
`

func (q *Queries) GetMemoryChildren(ctx context.Context, parentID pgtype.UUID) ([]Memory, error) {
	rows, err := q.db.Query(ctx, getMemoryChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Type,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryRootChildren = `-- name: GetMemoryRootChildren :many
SELECT id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM memories
WHERE parent_id IS NULL
  AND archive_id = $1
ORDER BY kind ASC, title ASC
`

func (q *Queries) GetMemoryRootChildren(ctx context.Context, archiveID pgtype.UUID) ([]Memory, error) {
	rows, err := q.db.Query(ctx, getMemoryRootChildren, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Type,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemories = `-- name: ListMemories :many
SELECT id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM memories
WHERE (archive_id = $1 OR $1 IS NULL)
  AND (parent_id = $2 OR ($2 IS NULL AND parent_id IS NULL))
  AND (kind = $3 OR $3 = '')
  AND (type = $4 OR $4 = '')
  AND (visibility = $5 OR $5 = '')
  AND (author = $6 OR $6 = '')
ORDER BY created_at DESC
LIMIT $7 OFFSET $8
`

type ListMemoriesParams struct {
	ArchiveID  pgtype.UUID `json:"archive_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Kind       string      `json:"kind"`
	Type       string      `json:"type"`
	Visibility string      `json:"visibility"`
	Author     string      `json:"author"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListMemories(ctx context.Context, arg ListMemoriesParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemories,
		arg.ArchiveID,
		arg.ParentID,
		arg.Kind,
		arg.Type,
		arg.Visibility,
		arg.Author,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Type,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at FROM memories
WHERE search_vector @@ plainto_tsquery('simple', $1)
  AND (archive_id = $2 OR $2 IS NULL)
  AND (visibility = $3 OR $3 = '')
  AND (author = $4 OR $4 = '')
ORDER BY ts_rank(search_vector, plainto_tsquery('simple', $1)) DESC
`

type SearchMemoriesParams struct {
	PlaintoTsquery string      `json:"plainto_tsquery"`
	ArchiveID      pgtype.UUID `json:"archive_id"`
	Visibility     string      `json:"visibility"`
	Author         string      `json:"author"`
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, searchMemories,
		arg.PlaintoTsquery,
		arg.ArchiveID,
		arg.Visibility,
		arg.Author,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.ArchiveID,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.Type,
			&i.Tags,
			&i.Author,
			&i.Visibility,
			&i.SharedWith,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories
SET title       = COALESCE($2, title),
    content     = COALESCE($3, content),
    summary     = COALESCE($4, summary),
    type        = COALESCE($5, type),
    tags        = COALESCE($6, tags),
    visibility  = COALESCE($7, visibility),
    shared_with = COALESCE($8, shared_with),
    attachments = COALESCE($9, attachments),
    parent_id   = COALESCE($10, parent_id),
    kind        = COALESCE($11, kind),
    updated_at  = now()
WHERE id = $1
RETURNING id, archive_id, parent_id, kind, title, content, summary, type, tags, author, visibility, shared_with, attachments, created_at, updated_at
`

type UpdateMemoryParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Summary     string      `json:"summary"`
	Type        string      `json:"type"`
	Tags        []byte      `json:"tags"`
	Visibility  string      `json:"visibility"`
	SharedWith  []byte      `json:"shared_with"`
	Attachments []byte      `json:"attachments"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Kind        string      `json:"kind"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.Type,
		arg.Tags,
		arg.Visibility,
		arg.SharedWith,
		arg.Attachments,
		arg.ParentID,
		arg.Kind,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.ArchiveID,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.Type,
		&i.Tags,
		&i.Author,
		&i.Visibility,
		&i.SharedWith,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
