// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Archive struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        string             `json:"icon"`
	Author      string             `json:"author"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ChatHistory struct {
	ID        int32              `json:"id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	ToolCalls []byte             `json:"tool_calls"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Directive struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Status        string             `json:"status"`
	Priority      string             `json:"priority"`
	Assignee      string             `json:"assignee"`
	Author        string             `json:"author"`
	RequireDocIds []byte             `json:"require_doc_ids"`
	NarrativeID   string             `json:"narrative_id"`
	ArchiveID     pgtype.UUID        `json:"archive_id"`
	Visibility    string             `json:"visibility"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DocumentLink struct {
	ID           pgtype.UUID        `json:"id"`
	SourceID     pgtype.UUID        `json:"source_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	RelationType string             `json:"relation_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Memory struct {
	ID          pgtype.UUID        `json:"id"`
	ArchiveID   pgtype.UUID        `json:"archive_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Kind        string             `json:"kind"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Summary     string             `json:"summary"`
	Type        string             `json:"type"`
	Tags        []byte             `json:"tags"`
	Author      string             `json:"author"`
	Visibility  string             `json:"visibility"`
	SharedWith  []byte             `json:"shared_with"`
	Attachments []byte             `json:"attachments"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
