// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Archive struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        string             `json:"icon"`
	Author      string             `json:"author"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Doc struct {
	ID          pgtype.UUID        `json:"id"`
	ArchiveID   pgtype.UUID        `json:"archive_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Summary     string             `json:"summary"`
	Status      *string            `json:"status"`
	Priority    *string            `json:"priority"`
	Assignee    string             `json:"assignee"`
	Tags        []byte             `json:"tags"`
	Author      string             `json:"author"`
	Visibility  string             `json:"visibility"`
	SharedWith  []byte             `json:"shared_with"`
	Attachments []byte             `json:"attachments"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DocLink struct {
	ID           pgtype.UUID        `json:"id"`
	SourceID     pgtype.UUID        `json:"source_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	RelationType string             `json:"relation_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
