// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_keys.sql

package hostgen

import (
	"context"
)

const createGitKey = `-- name: CreateGitKey :one
INSERT INTO git_keys (name, encrypted_token, token_mask)
VALUES ($1, $2, $3)
RETURNING id, name, encrypted_token, token_mask, created_at, updated_at
`

type CreateGitKeyParams struct {
	Name           string `json:"name"`
	EncryptedToken string `json:"encrypted_token"`
	TokenMask      string `json:"token_mask"`
}

func (q *Queries) CreateGitKey(ctx context.Context, arg CreateGitKeyParams) (GitKey, error) {
	row := q.db.QueryRow(ctx, createGitKey, arg.Name, arg.EncryptedToken, arg.TokenMask)
	var i GitKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedToken,
		&i.TokenMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitKeyByName = `-- name: DeleteGitKeyByName :exec
DELETE FROM git_keys WHERE name = $1
`

func (q *Queries) DeleteGitKeyByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteGitKeyByName, name)
	return err
}

const getGitKeyByName = `-- name: GetGitKeyByName :one
SELECT id, name, encrypted_token, token_mask, created_at, updated_at FROM git_keys WHERE name = $1
`

func (q *Queries) GetGitKeyByName(ctx context.Context, name string) (GitKey, error) {
	row := q.db.QueryRow(ctx, getGitKeyByName, name)
	var i GitKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedToken,
		&i.TokenMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitKeys = `-- name: ListGitKeys :many
SELECT id, name, encrypted_token, token_mask, created_at, updated_at FROM git_keys ORDER BY name ASC
`

func (q *Queries) ListGitKeys(ctx context.Context) ([]GitKey, error) {
	rows, err := q.db.Query(ctx, listGitKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitKey
	for rows.Next() {
		var i GitKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EncryptedToken,
			&i.TokenMask,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
