// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_servers.sql

package hostgen

import (
	"context"
)

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (name, type, command, url, args, env)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, command, url, args, env, created_at, updated_at
`

type CreateMCPServerParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Command string `json:"command"`
	Url     string `json:"url"`
	Args    []byte `json:"args"`
	Env     []byte `json:"env"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.Name,
		arg.Type,
		arg.Command,
		arg.Url,
		arg.Args,
		arg.Env,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Command,
		&i.Url,
		&i.Args,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPServerByName = `-- name: DeleteMCPServerByName :exec
DELETE FROM mcp_servers WHERE name = $1
`

func (q *Queries) DeleteMCPServerByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteMCPServerByName, name)
	return err
}

const getMCPServerByName = `-- name: GetMCPServerByName :one
SELECT id, name, type, command, url, args, env, created_at, updated_at FROM mcp_servers WHERE name = $1
`

func (q *Queries) GetMCPServerByName(ctx context.Context, name string) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerByName, name)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Command,
		&i.Url,
		&i.Args,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT id, name, type, command, url, args, env, created_at, updated_at FROM mcp_servers ORDER BY name ASC
`

func (q *Queries) ListMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Command,
			&i.Url,
			&i.Args,
			&i.Env,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers
SET type = $2, command = $3, url = $4, args = $5, env = $6, updated_at = NOW()
WHERE name = $1
RETURNING id, name, type, command, url, args, env, created_at, updated_at
`

type UpdateMCPServerParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Command string `json:"command"`
	Url     string `json:"url"`
	Args    []byte `json:"args"`
	Env     []byte `json:"env"`
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.Name,
		arg.Type,
		arg.Command,
		arg.Url,
		arg.Args,
		arg.Env,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Command,
		&i.Url,
		&i.Args,
		&i.Env,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
