// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package hostgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEntry struct {
	ID             int64              `json:"id"`
	AuditID        string             `json:"audit_id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	Operator       string             `json:"operator"`
	TargetNode     string             `json:"target_node"`
	Action         string             `json:"action"`
	PayloadSummary string             `json:"payload_summary"`
	Result         string             `json:"result"`
	StatusCode     int32              `json:"status_code"`
}

type GitKey struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	EncryptedToken string             `json:"encrypted_token"`
	TokenMask      string             `json:"token_mask"`
	TokenType      string             `json:"token_type"`
	Host           *string            `json:"host"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type HostSpec struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Tools       []byte             `json:"tools"`
	Resources   []byte             `json:"resources"`
	Skills      []byte             `json:"skills"`
	McpServers  []byte             `json:"mcp_servers"`
	Rules       []byte             `json:"rules"`
	GitKeys     []byte             `json:"git_keys"`
	AuthToken   string             `json:"auth_token"`
	Status      string             `json:"status"`
	ErrorMsg    string             `json:"error_msg"`
	RetryCount  int32              `json:"retry_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type HostToken struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type McpServer struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Command   string             `json:"command"`
	Url       string             `json:"url"`
	Args      []byte             `json:"args"`
	Env       []byte             `json:"env"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Node struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Address       string             `json:"address"`
	ExternalAddr  string             `json:"external_addr"`
	GrpcAddress   string             `json:"grpc_address"`
	Status        string             `json:"status"`
	Capabilities  []byte             `json:"capabilities"`
	AgentStatus   []byte             `json:"agent_status"`
	Metadata      []byte             `json:"metadata"`
	RegisteredAt  pgtype.Timestamptz `json:"registered_at"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
}

type Rule struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Skill struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
