// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package hostgen

import (
	"context"
)

const countNodes = `-- name: CountNodes :one
SELECT COUNT(*) FROM nodes
`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOnlineNodes = `-- name: CountOnlineNodes :one
SELECT COUNT(*) FROM nodes
WHERE last_heartbeat > NOW() - INTERVAL '30 seconds'
`

func (q *Queries) CountOnlineNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOnlineNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHostTokenByName = `-- name: DeleteHostTokenByName :exec
DELETE FROM host_tokens WHERE name = $1
`

func (q *Queries) DeleteHostTokenByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteHostTokenByName, name)
	return err
}

const deleteNodeByName = `-- name: DeleteNodeByName :exec
DELETE FROM nodes WHERE name = $1
`

func (q *Queries) DeleteNodeByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteNodeByName, name)
	return err
}

const getHostTokenByName = `-- name: GetHostTokenByName :one
SELECT token FROM host_tokens WHERE name = $1
`

func (q *Queries) GetHostTokenByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getHostTokenByName, name)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT id, name, address, external_addr, grpc_address, status, capabilities, agent_status, metadata, registered_at, last_heartbeat FROM nodes WHERE name = $1
`

func (q *Queries) GetNodeByName(ctx context.Context, name string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByName, name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ExternalAddr,
		&i.GrpcAddress,
		&i.Status,
		&i.Capabilities,
		&i.AgentStatus,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeat,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, address, external_addr, grpc_address, status, capabilities, agent_status, metadata, registered_at, last_heartbeat FROM nodes ORDER BY name ASC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ExternalAddr,
			&i.GrpcAddress,
			&i.Status,
			&i.Capabilities,
			&i.AgentStatus,
			&i.Metadata,
			&i.RegisteredAt,
			&i.LastHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :one
UPDATE nodes
SET agent_status = $2,
    last_heartbeat = NOW(),
    status = 'online'
WHERE name = $1
RETURNING id, name, address, external_addr, grpc_address, status, capabilities, agent_status, metadata, registered_at, last_heartbeat
`

type UpdateNodeHeartbeatParams struct {
	Name        string `json:"name"`
	AgentStatus []byte `json:"agent_status"`
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeHeartbeat, arg.Name, arg.AgentStatus)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ExternalAddr,
		&i.GrpcAddress,
		&i.Status,
		&i.Capabilities,
		&i.AgentStatus,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeat,
	)
	return i, err
}

const updateNodeStatusOffline = `-- name: UpdateNodeStatusOffline :exec
UPDATE nodes SET status = 'offline'
WHERE name = $1 AND status = 'online' AND last_heartbeat < NOW() - INTERVAL '30 seconds'
`

func (q *Queries) UpdateNodeStatusOffline(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, updateNodeStatusOffline, name)
	return err
}

const upsertHostToken = `-- name: UpsertHostToken :exec
INSERT INTO host_tokens (name, token)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET token = EXCLUDED.token
`

type UpsertHostTokenParams struct {
	Name  string `json:"name"`
	Token string `json:"token"`
}

func (q *Queries) UpsertHostToken(ctx context.Context, arg UpsertHostTokenParams) error {
	_, err := q.db.Exec(ctx, upsertHostToken, arg.Name, arg.Token)
	return err
}

const upsertNode = `-- name: UpsertNode :one
INSERT INTO nodes (name, address, external_addr, grpc_address, capabilities, agent_status, metadata, status, registered_at, last_heartbeat)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'online', NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
    address = EXCLUDED.address,
    external_addr = EXCLUDED.external_addr,
    grpc_address = EXCLUDED.grpc_address,
    capabilities = EXCLUDED.capabilities,
    agent_status = EXCLUDED.agent_status,
    metadata = EXCLUDED.metadata,
    status = 'online',
    registered_at = NOW(),
    last_heartbeat = NOW()
RETURNING id, name, address, external_addr, grpc_address, status, capabilities, agent_status, metadata, registered_at, last_heartbeat
`

type UpsertNodeParams struct {
	Name         string `json:"name"`
	Address      string `json:"address"`
	ExternalAddr string `json:"external_addr"`
	GrpcAddress  string `json:"grpc_address"`
	Capabilities []byte `json:"capabilities"`
	AgentStatus  []byte `json:"agent_status"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.Name,
		arg.Address,
		arg.ExternalAddr,
		arg.GrpcAddress,
		arg.Capabilities,
		arg.AgentStatus,
		arg.Metadata,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ExternalAddr,
		&i.GrpcAddress,
		&i.Status,
		&i.Capabilities,
		&i.AgentStatus,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeat,
	)
	return i, err
}
