// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package hostgen

import (
	"context"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (name, content)
VALUES ($1, $2)
RETURNING id, name, content, created_at, updated_at
`

type CreateRuleParams struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule, arg.Name, arg.Content)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRuleByName = `-- name: DeleteRuleByName :exec
DELETE FROM rules WHERE name = $1
`

func (q *Queries) DeleteRuleByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRuleByName, name)
	return err
}

const getRuleByName = `-- name: GetRuleByName :one
SELECT id, name, content, created_at, updated_at FROM rules WHERE name = $1
`

func (q *Queries) GetRuleByName(ctx context.Context, name string) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleByName, name)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRulesByNames = `-- name: GetRulesByNames :many
SELECT id, name, content, created_at, updated_at FROM rules WHERE name = ANY($1::text[])
`

func (q *Queries) GetRulesByNames(ctx context.Context, dollar_1 []string) ([]Rule, error) {
	rows, err := q.db.Query(ctx, getRulesByNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, name, content, created_at, updated_at FROM rules ORDER BY name ASC
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET content = $2, updated_at = NOW()
WHERE name = $1
RETURNING id, name, content, created_at, updated_at
`

type UpdateRuleParams struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, updateRule, arg.Name, arg.Content)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
