// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package hostgen

import (
	"context"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (name, description, config)
VALUES ($1, $2, $3)
RETURNING id, name, description, config, created_at, updated_at
`

type CreateSkillParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Config      []byte `json:"config"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, arg.Name, arg.Description, arg.Config)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillByName = `-- name: DeleteSkillByName :exec
DELETE FROM skills WHERE name = $1
`

func (q *Queries) DeleteSkillByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteSkillByName, name)
	return err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, name, description, config, created_at, updated_at FROM skills WHERE name = $1
`

func (q *Queries) GetSkillByName(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByName, name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillsByNames = `-- name: GetSkillsByNames :many
SELECT id, name, description, config, created_at, updated_at FROM skills WHERE name = ANY($1::text[])
`

func (q *Queries) GetSkillsByNames(ctx context.Context, dollar_1 []string) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkillsByNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, description, config, created_at, updated_at FROM skills ORDER BY name ASC
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET description = $2, config = $3, updated_at = NOW()
WHERE name = $1
RETURNING id, name, description, config, created_at, updated_at
`

type UpdateSkillParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Config      []byte `json:"config"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill, arg.Name, arg.Description, arg.Config)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
