generatorName: typescript-fetch
inputSpec: ../cradle/api/gen/openapiv2/maze.swagger.json
outputDir: src/api/gen
additionalProperties:
  supportsES6: true
  stringEnums: true
  typescriptThreePlus: true
