FROM public.ecr.aws/docker/library/node:22-bookworm-slim AS builder
RUN npm install -g pnpm

COPY fabrication/deps/js.txt /tmp/js-deps.txt
RUN xargs -a /tmp/js-deps.txt -I {} npm install -g --prefix /opt/node {} || true

FROM scratch
COPY --from=builder /opt/node /opt/node
